### ISSUE TITLE
(Ingame)Verify Command not working.

### ISSUE THREAD

**Issue by ArmaniS-Dev** [yawek9/discordverifier#2]
First of all I would like to say that I really like the plugin. Only I can hardly see through the plugin because it is not very modular, e.g. Make more classes to use the functions there. Maybe use Mojang Bridigier. But now to my real mistake. There is no command to run /discord accept. Neither does /discord deny. It just doesn't exist. I think you forgot a few little things and then didn't feel like testing the plugin anymore. Whenever you type these commands, the only command that comes up there is when you type /discord. LG

**Comment by yawek9** [comment]
The plugin is pretty small for now and I don't think that modules for every command are that necessary. /discord accept and /discord deny commands works well for me. I have no idea what can cause that they don't work for you. I'm currently using the plugin for my purposes and I thought it would be useful for someone else. That's the reason why I've published it here. If you have any ideas, how to improve the plugin, I'm open for any suggestions. I also created the Discord server to provide better support. You can join it by the link: https://discord.gg/cpY2Qcjjcz.

**Comment by ArmaniS-Dev** [comment]
maybe it's because I changed the plugin to java 16. Otherwise I haven't changed anything. And I like the plugin, too, and I'm sure there will be people who will find it helpful.
